version: "3"
services:
    db:
        container_name: cherry-mysql
        image: mysql:5.7
        platform: linux/x86_64
        volumes:
            - "${MYSQL_HOME_DIR}:/var/lib/mysql:rw"
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        restart: always
        logging:
            options:
                max-size: "1m"
                max-file: "1"
    backend:
        container_name: cherry-spring
        image: openjdk:11.0.7-jre-slim
        volumes:
            - "${BACKEND_HOME_DIR}:/spring"
        working_dir: /spring
        command: ["java", "-jar", "./build/libs/${BACKEND_JAR_FILE}"]
        ports:
            - "8080:8080"
        depends_on:
            - db
        links:
            - db
        restart: always
        logging:
            options:
                max-size: "1m"
                max-file: "3"
    frontend:
        container_name: cherry-front
        image: nginx:1-alpine
        volumes:
            - "${FRONT_HOME_DIR}:/usr/share/nginx/html:rw"
        restart: always
        depends_on:
            - router
    router:
        container_name: cherry-nginx
        image: nginx:1-alpine
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf"
            - "${NGINX_LOG_DIR}:/var/log/nginx/:rw"
            - "${FRONT_HOME_DIR}:/usr/share/nginx/html:rw"
        depends_on:
            - backend
            - db
        restart: always
        logging:
            options:
                max-size: "1m"
                max-file: "3"
networks:
    default:
        external:
            name: cherry