spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
#
#cherry-front:
#  base-url: http://localhost:800